[env:esp32-s3-devkitc-1-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Spesifiserer N16R8 minneprofil
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB

; Serial monitor hastighet
monitor_speed = 115200

; Viktig for ESP32-S3 for å se Serial output
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; Biblioteker som trengs for StrideControl
lib_deps =
    knolleary/PubSubClient
    links2004/WebSockets @ ^2.4.1
    h2zero/NimBLE-Arduino @ ^1.4.2