; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = seeed_xiao_esp32s3
build_cache_dir = .cache
;default_envs = seeed_xiao_esp32s3, esp32-s3-devkitc-1-n16r8

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions_8MB.csv
board_build.filesystem = littlefs
monitor_speed = 115200
lib_ldf_mode = chain+
build_flags = 
	-Iinclude
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=3
	-DSTRIDECONTROL_TESTBENCH=1
	-mtext-section-literals
lib_deps = 
	knolleary/PubSubClient
	h2zero/NimBLE-Arduino @ ^1.4.2
	bblanchon/ArduinoJson @ ^7.0.4
	mathieucarbou/AsyncTCP @ ^3.2.4
	mathieucarbou/ESPAsyncWebServer @ ^3.1.5
lib_ignore = 
	WebServer
	WebSockets

;[env:esp32-s3-devkitc-1-n16r8]
;platform = espressif32
;board = esp32-s3-devkitc-1
;framework = arduino
;board_build.arduino.memory_type = qio_opi
;board_build.flash_mode = qio
;board_build.psram_type = opi
;board_upload.flash_size = 16MB
;board_build.partitions = partitions_16MB.csv
;board_build.filesystem = littlefs
;monitor_speed = 115200
;build_flags = 
;	-Iinclude
;	-DARDUINO_USB_MODE=1
;	-DARDUINO_USB_CDC_ON_BOOT=1
;	-DBOARD_HAS_PSRAM
;	-DCORE_DEBUG_LEVEL=3
;lib_deps = 
;	knolleary/PubSubClient
;	links2004/WebSockets @ ^2.4.1
;	h2zero/NimBLE-Arduino @ ^1.4.2
;	bblanchon/ArduinoJson @ ^7.0.4
;	mathieucarbou/AsyncTCP @ ^3.2.4
;	mathieucarbou/ESPAsyncWebServer @ ^3.1.5
;lib_ignore = 
;	WebServer

